name: testproject
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  go_router: ^6.2.0
  http: ^0.13.5
  responsive_framework: ^0.2.0
  connectivity_plus: ^3.0.3
  flutter_rating_bar: ^4.0.1
  get_it: ^7.2.0



  cupertino_icons: ^1.0.2
  flutter_localizations:
    sdk: flutter
  intl: any

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:
  generate: true


  uses-material-design: true

  assets:
    - assets/images/
  #   - images/a_dot_ham.jpeg

  fonts:
    - family: Anton
      fonts:
        - asset: assets/fonts/Anton/Anton-Regular.ttf

    - family: Mukta
      fonts:
        - asset: assets/fonts/Mukta/Mukta-Regular.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
